# platform :ios, '9.0'
use_frameworks!

target 'Binar' do
  pod 'Firebase/RemoteConfig'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'GoogleSignIn'

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
