# platform :ios, '9.0'
use_frameworks!

target 'Binar' do
  pod 'Firebase/RemoteConfig'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'GoogleSignIn'
  pod 'OneSignal', '3.11.1'
  
  target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '3.11.1'
  end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
	    config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
end
